### ISSUE TITLE
Incorrect translation va_list to VaList

### ISSUE THREAD

**Issue by aladagemre** [manastech/crystal_lib#13]
When creating binding for igraph,

the crystal_lib generates "alias VaList = LibC::VaList" statement but it says "undefined constant LibC::VaList" when I include the generated content. I have to replace it with: alias VaList = UInt8[24] then it works.

https://github.com/igraph/igraph/search?p=3&q=va_list&utf8=%E2%9C%93
See the generated code: https://github.com/aladagemre/crystal-igraph/blob/0ce58a79bdeab565af3dca6e19bcfbf2285b9b9c/lib_igraph.cr

one comment:  va_list is a variable list of arguments.  translating it to  LibC::VaList is incorrect.

**Comment by DmitryBochkarev** [comment]
current crystal master have LibC::VaList https://github.com/manastech/crystal/blob/master/src/libc.cr#L41

**Comment by aladagemre** [comment]
OK, it seems like its due to I'm using 0.9.1 (30 Oct) and the commit as made on Nov 3.
