### ISSUE TITLE
Generated code fails to compile due to including multiple definitions of a data structure.

### ISSUE THREAD

**Issue by samis** [manastech/crystal_lib#9]
(I had difficulty coming up with a good title for this.) Since #8 was fixed, the tool can now successfully parse and generate code for Eina.h which is excellent. The generated code even almost compiles without manual intervention :grinning:. However, there is one issue with the generated code: It defines the struct `X___Data` twice, causing it to fail to compile. The two definitions start [here](https://gist.github.com/samis/b4e30e7333dda83de08e#file-lib_eina-cr-L1189) and [here](https://gist.github.com/samis/b4e30e7333dda83de08e#file-lib_eina-cr-L1216) respectively.

**Comment by asterite** [comment]
@samis I'm not getting that definition. I use:

```crystal
@[Include("stdarg.h", "eina/Eina.h", flags: "-I/Users/asterite-manas/Sandbox/efl/src/lib", prefix: %w(eina_))]
@[Link("eina")]
lib LibEina
end
```

Maybe I need to include more `.h` files? What `Include` are you using?

**Comment by asterite** [comment]
In my case `/Users/asterite-manas/Sandbox/efl` contains the git checkout for the efl project, https://git.enlightenment.org/core/efl.git/tree

**Comment by samis** [comment]
I'll perform further testing then to see if I can achieve the same result.

**Comment by samis** [comment]
Right. Even with the following `Include` it still generates the data structure:
```
@[Include("/home/samis/develop/efl/src/lib/eina/Eina.h", flags: "-I/home/samis/develop/efl/src/lib/", prefix: %w(eina_))]
```
The directory given is a fresh clone of the the git repository.
I even more my system copy of the headers out of the way in order to eliminate them. I'm going to see exactly which file causes this to happen.

**Comment by asterite** [comment]
Oh, it's working fine on mac osx. The problem seems to happen in linux. I'll try to reproduce it, seems like a bug in nested fields.

**Comment by samis** [comment]
I've narrowed it down to the contents of `eina_lock.h`. I'll see if I can narrow it down to the specific functions causing it.

**Comment by asterite** [comment]
@samis Can you check now? I think I fixed it

**Comment by samis** [comment]
It seems to be fixed, I'll take a more indepth-look in a moment.

**Comment by samis** [comment]
Yep, this appears to be fixed now.

**Comment by asterite** [comment]
\o/
